### ISSUE TITLE
test fails in zsh

### ISSUE THREAD

**Issue by b4b4r07** [bucaran/getopts#8]
See https://travis-ci.org/b4b4r07/getopts/builds/100612982

I wonder why?

**Comment by bucaran** [comment]
Because maybe the order matters in zspec, while it does not in the way I wrote the tests with Fishtape.

In Fishtape
```
test
    a = a b c # TRUE, because a is ***in*** the list a,b,c
end

test
    a b c = a # FALSE
end
```

To Fishtape, the following is acceptable.

```
 [ "a" "b 42" "_ beer" "foo" "bar" ] === [ "_ beer" "b 42" "a" "foo" "bar" ]
```

**Comment by bucaran** [comment]
Maybe just try:

```
    it "bare does not end opts"
        expects=( "_ beer" "b 42" "a" "foo" "bar" )
        actuals=( "${(@f)"$(getopts beer -ab42 beer --foo --bar)"}" )
        ret=$status
        array --a $expects --b $actuals
        assert equal "$ret" "0"
    end
```

**Comment by b4b4r07** [comment]
Thank you for your quick reply.

I got it! I'll improve zspec and rewrite my tests.

**Comment by bucaran** [comment]
@b4b4r07 I don't think there is a problem with zspec! This is a Fishtape specific behavio, simply because I wanted to have such feature.

Thanks for reporting this and thanks for writing the zspec tests?
